In [1]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [3]:

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:


arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


0-D

In [6]:


arr = np.array(42)

print(arr)

42


1-D

In [7]:


arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


2-D

In [8]:


arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


3-D

In [9]:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


convert to dimensions

In [11]:


arr = np.array([1, 2, 3, 4], ndmin=3)

print(arr)
print('number of dimensions :', arr.ndim)

[[[1 2 3 4]]]
number of dimensions : 3


In [14]:

arr = np.array([[[1,2,3,4],[3,4,5,6]],[[1,2,3,4],[3,4,5,8]]])

print(arr[1][-1])

[3 4 5 8]


pandas

In [16]:
import pandas as pd

df = pd.read_csv('homeprices.csv')

print(df.to_string()) 

   area  rooms  age   price
0  2600    3.0   20  550000
1  3000    4.0   15  565000
2  3200    NaN   18  610000
3  3600    3.0   30  595000
4  4000    5.0    8  760000
5  4100    6.0    8  810000
